[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
reward_distributor = "3jjbW21zG4faJLnGfJdxGe49NnikRXyeJraBPhJLT7uW"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
